apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: playground
  description: |
    This accelerator provides Terraform modules to provision Databricks workspaces,
        compute, Unity Catalog, metastores, and security configurations, designed to be
        composed together for tailored deployments.
  tags:
    - databricks
    - terraform
    - aws
    - oidc
spec:
  owner: group:accelerator-publisher
  type: service
  parameters:
    - title: Module Configuration
      description: Select modules to configure and provide their settings
      required:
        - isWorkspaceEnabled
      properties:
        isWorkspaceEnabled:
          title: Enable Workspace Module?
          type: boolean
          default: false
        isCatalogEnabled:
          title: Enable Catalog Module?
          type: boolean
          default: false
        isComputeEnabled:
          title: Enable Compute Module?
          type: boolean
          default: false
        isSecurityEnabled:
          title: Enable Security Module?
          type: boolean
          default: false
        isCiCdEnabled:
          title: Enable CI/CD Module?
          type: boolean
          default: false
      dependencies:
        isWorkspaceEnabled:
          oneOf:
            - properties:
                isWorkspaceEnabled:
                  const: false
            - properties:
                isWorkspaceEnabled:
                  const: true
                workspaceName:
                  title: Workspace Name
                  type: string
                  default: thoughtworks-main
                  description: Name for the Databricks workspace
                enablePrivateAccess:
                  title: Enable Private Access
                  type: boolean
                  default: true
                s3BucketPrefix:
                  title: S3 Bucket Prefix
                  type: string
                  default: thoughtworks
                  description: Prefix for S3 bucket names
                databricksCrossAccountPolicyType:
                  title: Cross Account Policy Type
                  type: string
                  default: customer
        isCatalogEnabled:
          oneOf:
            - properties:
                isCatalogEnabled:
                  const: false
            - properties:
                isCatalogEnabled:
                  const: true
                catalogName:
                  title: Catalog Name
                  type: string
                  default: main_catalog
                  description: Name for the Unity Catalog
                enableExternalLocation:
                  title: Enable External Location
                  type: boolean
                  default: true
                s3Prefix:
                  title: S3 Prefix
                  type: string
                  default: thoughtworks
                  description: S3 prefix for catalog storage
        isComputeEnabled:
          oneOf:
            - properties:
                isComputeEnabled:
                  const: false
            - properties:
                isComputeEnabled:
                  const: true
                computeClusterType:
                  title: Compute Cluster Type
                  type: string
                  default: Standard
                  description: Type of compute cluster
                enableAutoTerminate:
                  title: Enable Auto Terminate
                  type: boolean
                  default: true
        isSecurityEnabled:
          oneOf:
            - properties:
                isSecurityEnabled:
                  const: false
            - properties:
                isSecurityEnabled:
                  const: true
                securityLevel:
                  title: Security Level
                  type: string
                  default: high
                  description: Level of security enforcement
        isCiCdEnabled:
          oneOf:
            - properties:
                isCiCdEnabled:
                  const: false
            - properties:
                isCiCdEnabled:
                  const: true
                pipelineName:
                  title: Pipeline Name
                  type: string
                  default: main_pipeline
                  description: Name of the CI/CD pipeline

  steps:
    - id: fetch-base
      name: Fetch Base
      action: fetch:plain
      input:
        url: ./skeleton
  
    - id: publish
      name: Publish to GitHub
      action: publish:github
      input:
        allowedHosts: [ 'github.com' ]
        repoUrl: ${{ parameters.repoUrl }}
        repoVisibility: private
        defaultBranch: main
        token: ${{ secrets.USER_OAUTH_TOKEN or false }}
        description: Databricks Terraform Accelerator
        secrets:
          DATABRICKS_CLIENT_SECRET: ${{ secrets.databricksClientSecret }}
        repoVariables:
          DATABRICKS_HOST: ${{ parameters.databricksHost }}
          DATABRICKS_CLIENT_ID: ${{ parameters.databricksClientId }}
          AWS_REGION: ${{ parameters.awsRegion }}
          AWS_ROLE_TO_ASSUME: ${{ parameters.awsOidcRoleArn }}
          TF_BACKEND_BUCKET: ${{ parameters.tfStateBucket }}
          TF_VAR_s3_bucket_name_main: ${{ parameters.appS3BucketName }}   

  output:
    links:
      - title: GitHub Repository
        icon: github
        url: ${{ steps.publish.output.remoteUrl }}
