title: Catalog Module Configuration
description: Configure Unity Catalog settings
properties:
  catalogName:
    title: Catalog Name
    type: string
    description: Name for the Unity Catalog
    default: main_catalog
  
  enableExternalLocation:
    title: Enable External Location
    type: boolean
    default: true
  
  s3Prefix:
    title: S3 Prefix
    type: string
    default: thoughtworks
    description: S3 prefix for catalog storage
