title: CI/CD and Environment Configuration
required:
  - tfStateBucket
  - awsRegion
  - awsOidcRoleArn
  - databricksClientId
  - databricksClientSecret
  - appS3BucketName
properties:
    repoUrl:
      title: Target Repository Location
      type: string
      ui:field: RepoUrlPicker
      ui:options:
        requestUserCredentials:
          secretsKey: USER_OAUTH_TOKEN
          additionalScopes:
            github:
              - workflow
        allowedHosts:
          - github.com
    tfStateBucket:
      title: Terraform State S3 Bucket Name
      type: string
      description: "Name of the S3 bucket to store Terraform state files."
    appS3BucketName:
      title: Application S3 Bucket Name
      type: string
      description: "Name of the main S3 bucket for application data storage."
    awsRegion:
      title: AWS Region
      type: string
      description: "AWS region for deploying resources and for the S3 state bucket (e.g., us-west-1)."
      default: us-west-1
    awsOidcRoleArn:
      title: AWS OIDC Role ARN
      type: string
      description: "ARN of the IAM Role for GitHub Actions OIDC authentication (e.g., arn:aws:iam::123456789012:role/GitHubActionsRole)."
    databricksAccountId:
      title: Databricks Account Id
      type: string
      description: "Account ID of the Databricks"
    databricksHost:
      title: Databricks Host
      type: string
      description: "Databricks workspace URL (e.g., https://dbc-12345678-abcd.cloud.databricks.com)"
    databricksClientId:
      title: Databricks Client ID
      type: string
      description: "Client ID for the Databricks Service Principal."
    databricksClientSecret:
      title: Databricks Client Secret
      type: string
      description: "Client Secret for the Databricks Service Principal."
      ui:field: Secret
