title: Workspace Module Configuration
description: Configure Databricks Workspace settings
properties:
  workspaceName:
    title: Workspace Name
    type: string
    description: Name for the Databricks workspace
    default: thoughtworks-main
  
  enablePrivateAccess:
    title: Enable Private Access
    type: boolean
    default: true
  
  s3BucketPrefix:
    title: S3 Bucket Prefix
    type: string
    default: thoughtworks
    description: Prefix for S3 bucket names
  
  databricksCrossAccountPolicyType:
    type: string
    title: Cross Account Policy Type
    default: customer 