# This entire file is now conditional on 'enable_metastore_security_config' from software_template.yaml
if:
  properties:
    enable_metastore_security_config: { const: true } # Check the global toggle for this module
then:
  # --- ORIGINAL CONTENT of metastore_security_config_parameters.yaml STARTS HERE ---
  title: Metastore Module Configuration
  description: Configure Unity Catalog Metastore
  required: []
  properties:
    enableMetaStoreStorage:
      title: Enable Storage Configuration
      type: boolean
      default: false
  dependencies:
    enableMetaStoreStorage:
      allOf:
        - if:
            properties:
              enableMetaStoreStorage:
                const: true
          then:
            properties:
              metastoreStorage:
                title: Storage Configuration
                type: object
                description: Storage Configuration
                properties:
                  s3_prefix:
                    title: S3 Prefix
                    type: string
                    default: thoughtworks
                  s3_versioning:
                    title: S3 Versioning
                    type: boolean
                    default: true
  # --- ORIGINAL CONTENT of metastore_security_config_parameters.yaml ENDS HERE ---
else:
  # If 'enable_metastore_security_config' (the global toggle) is false,
  # this entire file should contribute no active UI schema elements.
  properties: {}
  additionalProperties: false