title: Workspace Module Configuration
properties:
  isWorkspaceEnabled:
    title: Enable Workspace?
    type: boolean
    default: false
  # workspace is defined here, its schema will be set by if/then/else

if:
  properties:
    isWorkspaceEnabled: { const: true }
then:
  properties:
    isWorkspaceEnabled: { type: boolean } # Keep isWorkspaceEnabled in this branch's properties
    workspace: # Define the object schema for workspace
      title: Configuration
      type: object
      properties:
        databricksCredential:
          title: Databricks Credential
          type: object
          properties:
            databricksCrossAccountPolicyType:
              type: string
              title: Cross Account Policy Type
              default: customer
        databricksStorages:
          title: Databricks Storage
          type: array
          minItems: 1
          ui:options:
            addable: true
            orderable: true
            removable: true
          items:
            type: object
            properties:
              name:
                title: Name
                type: string
              s3_prefix:
                title: S3 prefix
                type: string
          default:
            - name: main
              s3_prefix: thoughtworks
            - name: finance
        databricksEncryptions:
          title: Databricks Encryptions
          type: array
          minItems: 1
          ui:options:
            addable: true
            orderable: true
            removable: true
            expandable: true
          items:
            type: object
            properties:
              name:
                title: Name
                type: string
              use_cases:
                title: Use Cases
                type: array
                items:
                  type: string
                  enum:
                    - MANAGED_SERVICES
                    - STORAGE
                uniqueItems: true
                ui:widget: checkboxes
          default:
            - name: main
              use_cases: 
                - MANAGED_SERVICES
                - STORAGE
            - name: dbfs
              use_cases: 
                - MANAGED_SERVICES
        workspaceConfiguration:
          title: Workspace
          type: array
          minItems: 1
          ui:options:
            addable: true
            orderable: true
            removable: true
            expandable: true
          items:
            type: object
            properties:
              name:
                title: Name
                type: string
              storage:
                title: Storage
                type: string
                enum: ["main", "finance"]  
              network:
                title: Network
                type: string
              private_access:
                title: Private Access
                type: boolean
                ui:widget: radio
              encryption:
                title: Encryption
                type: object
                properties:
                  storage:
                    title: Storage
                    type: string
          default:
            - name: thoughtworks-main
              storage: main
              network: main
              private_access: true
              encryption:
                storage: dbfs
            - name: thoughtworks-finance
              storage: finance
              network: finance
        clustersConfiguration:
          title: Clusters
          type: array
          minItems: 1
          ui:options:
            addable: true
            orderable: true
            removable: true
            expandable: true
          items:
            type: object
            properties:
              name:
                title: Name
                type: string
              spark_version:
                title: Spark Version
                type: string
              photon:
                title: Enable Photon
                type: boolean
              driver_instance_type:
                title: Driver Instance Type
                type: string
              instance_type:
                title: Worker Instance Type
                type: string
              spark_conf:
                title: Spark Configuration
                type: object
                properties:
                  spark_app_name:
                    title: Spark App Name
                    type: string
              on_demand:
                title: On-Demand Configuration
                type: object
                properties:
                  composition:
                    title: Composition
                    type: string
                    enum: [DRIVER_ONLY]
                  bid_price_percentage:
                    title: Bid Price Percentage
                    type: integer
              auto_terminate:
                title: Auto Terminate (minutes)
                type: integer
          default:
            - name: Shared Cluster
              spark_version: LTS
              photon: true
              driver_instance_type: m5.large
              instance_type: m5.xlarge
              spark_conf:
                spark_app_name: general_tasks
              on_demand:
                composition: DRIVER_ONLY
                bid_price_percentage: 100
              auto_terminate: 60
        sqlWarehousesConfiguration:
          title: SQL Warehouses
          type: array
          minItems: 1
          ui:options:
            addable: true
            orderable: true
            removable: true
            expandable: true
          items:
            type: object
            properties:
              name:
                title: Name
                type: string
              size:
                title: Size
                type: string
                enum: [Small, Medium, Large]
              photon:
                title: Enable Photon
                type: boolean
              serverless:
                title: Enable Serverless
                type: boolean
              min_clusters:
                title: Minimum Clusters
                type: integer
              max_clusters:
                title: Maximum Clusters
                type: integer
              spot_instance_policy:
                title: Spot Instance Policy
                type: string
                enum: [COST_OPTIMIZED, RELIABILITY_OPTIMIZED]
              auto_terminate:
                title: Auto Terminate (minutes)
                type: integer
          default:
            - name: SQL Shared
              size: Small
              photon: true
              serverless: true
              min_clusters: 2
              max_clusters: 3
              spot_instance_policy: COST_OPTIMIZED
              auto_terminate: 60
  required: [isWorkspaceEnabled, workspace] 
else: # isWorkspaceEnabled is false
  properties:
    isWorkspaceEnabled: { type: boolean } # Keep isWorkspaceEnabled in this branch's properties
    # workspace is NOT defined in properties here
  required: [isWorkspaceEnabled] # Only isWorkspaceEnabled is required
  additionalProperties: false # Forbids any properties not listed above (i.e., forbids workspace)
