# This entire file is now conditional on 'enable_workspace_config' from software_template.yaml
if:
  properties:
    enable_workspace_config: { const: true } # Check the global toggle for this module
then:
  # --- If enable_workspace_config is true, show all workspace parameters directly ---
  title: Workspace Module Configuration 
  properties:
    # The internal 'isWorkspaceEnabled' toggle has been removed.
    # The 'workspace' object is now a direct property.
    workspace: 
      title: Workspace Object Configuration
      type: object
      # All parameters previously under the internal 'isWorkspaceEnabled: true' branch
      # are now direct properties of this 'workspace' object.
      properties:
        databricksCredential:
          title: Databricks Credential
          type: object
          properties:
            databricksCrossAccountPolicyType:
              type: string
              title: Cross Account Policy Type
              default: customer
        databricksStorages:
          title: Databricks Storage
          type: array
          minItems: 1
          ui:options:
            addable: true
            orderable: true
            removable: true
          items:
            type: object
            properties:
              name:
                title: Name
                type: string
              s3_prefix:
                title: S3 prefix
                type: string
          default:
            - name: main
              s3_prefix: thoughtworks
            - name: finance
        databricksEncryptions:
          title: Databricks Encryptions
          type: array
          minItems: 1
          ui:options:
            addable: true
            orderable: true
            removable: true
            expandable: true
          items:
            type: object
            properties:
              name:
                title: Name
                type: string
              use_cases:
                title: Use Cases
                type: array
                items:
                  type: string
                  enum:
                    - MANAGED_SERVICES
                    - STORAGE
                  uniqueItems: true
                  ui:widget: checkboxes
            default:
              - name: main
                use_cases: 
                  - MANAGED_SERVICES
                  - STORAGE
              - name: dbfs
                use_cases: 
                  - MANAGED_SERVICES
        workspaceConfiguration:
          title: Workspace
          type: array
          minItems: 1
          ui:options:
            addable: true
            orderable: true
            removable: true
            expandable: true
          items:
            type: object
            properties:
              name:
                title: Name
                type: string
              storage:
                title: Storage
                type: string
                enum: ["main", "finance"]  
              network:
                title: Network
                type: string
              private_access:
                title: Private Access
                type: boolean
                ui:widget: radio
              encryption:
                title: Encryption
                type: object
                properties:
                  storage:
                    title: Storage
                    type: string
            default:
              - name: thoughtworks-main
                storage: main
                network: main
                private_access: true
                encryption:
                  storage: dbfs
              - name: thoughtworks-finance
                storage: finance
                network: finance
        clustersConfiguration:
          title: Clusters
          type: array
          minItems: 1
          ui:options:
            addable: true
            orderable: true
            removable: true
            expandable: true
          items:
            type: object
            properties:
              name:
                title: Name
                type: string
              spark_version:
                title: Spark Version
                type: string
              photon:
                title: Enable Photon
                type: boolean
              driver_instance_type:
                title: Driver Instance Type
                type: string
              instance_type:
                title: Worker Instance Type
                type: string
              spark_conf:
                title: Spark Configuration
                type: object
                properties:
                  spark_app_name:
                    title: Spark App Name
                    type: string
              on_demand:
                title: On-Demand Configuration
                type: object
                properties:
                  composition:
                    title: Composition
                    type: string
                    enum: [DRIVER_ONLY]
                  bid_price_percentage:
                    title: Bid Price Percentage
                    type: integer
              auto_terminate:
                title: Auto Terminate (minutes)
                type: integer
            default:
              - name: Shared Cluster
                spark_version: LTS
                photon: true
                driver_instance_type: m5.large
                instance_type: m5.xlarge
                spark_conf:
                  spark_app_name: general_tasks
                on_demand:
                  composition: DRIVER_ONLY
                  bid_price_percentage: 100
                auto_terminate: 60
        sqlWarehousesConfiguration:
          title: SQL Warehouses
          type: array
          minItems: 1
          ui:options:
            addable: true
            orderable: true
            removable: true
            expandable: true
          items:
            type: object
            properties:
              name:
                title: Name
                type: string
              size:
                title: Size
                type: string
                enum: [Small, Medium, Large]
              photon:
                title: Enable Photon
                type: boolean
              serverless:
                title: Enable Serverless
                type: boolean
              min_clusters:
                title: Minimum Clusters
                type: integer
              max_clusters:
                title: Maximum Clusters
                type: integer
              spot_instance_policy:
                title: Spot Instance Policy
                type: string
                enum: [COST_OPTIMIZED, RELIABILITY_OPTIMIZED]
              auto_terminate:
                title: Auto Terminate (minutes)
                type: integer
            default:
              - name: SQL Shared
                size: Small
                photon: true
                serverless: true
                min_clusters: 2
                max_clusters: 3
                spot_instance_policy: COST_OPTIMIZED
                auto_terminate: 60
  required: 
    - workspace # The 'workspace' object itself is now directly required if the module is enabled
  # The internal if/then/else for 'isWorkspaceEnabled' has been removed.
  # --- End of simplified content for the 'then' branch ---
else:
  # If 'enable_workspace_config' (the global toggle) is false,
  # this entire file should contribute no active UI schema elements.
  properties: {}
  additionalProperties: false
